"""make_source_url_unique_and_required

Revision ID: 54c3d0d13471
Revises: 3eefede41610
Create Date: 2026-05-12 02:22:42.127841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c3d0d13471'
down_revision: Union[str, None] = '3eefede41610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
