"""added  image_url, duration, and suggestion logic

Revision ID: 6ca649c145da
Revises: 8987749719ee
Create Date: 2026-04-26 00:18:56.993854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca649c145da'
down_revision: Union[str, None] = '8987749719ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('news', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_index('ix_news_category', table_name='news')
    op.create_foreign_key(None, 'news', 'categories', ['category_id'], ['id'])
    op.drop_column('news', 'category')
    op.add_column('podcasts', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('user_clicks', sa.Column('is_suggested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_clicks', 'is_suggested')
    op.drop_column('podcasts', 'duration')
    op.add_column('news', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_index('ix_news_category', 'news', ['category'], unique=False)
    op.drop_column('news', 'image_url')
    op.drop_column('news', 'category_id')
    # ### end Alembic commands ###
